services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - project_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    links:
      - db:db
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - project_network
    depends_on:
      - db
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

networks:
      project_network:
          driver: bridge