"""Unique DoneTasks: task_id and date

Revision ID: 14453939fdef
Revises: 86b0fed4843e
Create Date: 2024-09-17 20:11:04.992031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14453939fdef'
down_revision: Union[str, None] = '86b0fed4843e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_task_id_date', 'done_tasks', ['task_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_id_date', 'done_tasks', type_='unique')
    # ### end Alembic commands ###
