"""Categories-unique

Revision ID: a99f017e54cf
Revises: 2d89ddabc35c
Create Date: 2024-09-13 20:20:12.771822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99f017e54cf'
down_revision: Union[str, None] = '2d89ddabc35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_title_user_id', 'categories', ['title', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_title_user_id', 'categories', type_='unique')
    # ### end Alembic commands ###
